# Generated by Django 5.0.6 on 2024-06-02 17:57

import Zoo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0003_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[Zoo.models.CompanyInfo.validate_phone]),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='zooname',
            field=models.CharField(max_length=25, null=True, verbose_name='Zoo Name'),
        ),
    ]
