# Generated by Django 5.0.6 on 2024-06-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0005_faq_promocode_vacancy_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviary_number', models.IntegerField(null=True, unique=True)),
                ('aviary_name', models.CharField(max_length=100, null=True, verbose_name='aviary_name')),
                ('basin', models.BooleanField(default=False)),
                ('size_in_square_meters', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country_of_residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255, null=True, verbose_name=' feed_name')),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=255, null=True, verbose_name=' feed_name')),
                ('amount_kg', models.FloatField(null=True, verbose_name='Вес (кг)')),
                ('reciept_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_title', models.CharField(max_length=100, null=True, verbose_name='job title')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ward_animals',
            field=models.ManyToManyField(null=True, to='Zoo.kind_of_animal'),
        ),
        migrations.AddField(
            model_name='kind_of_animal',
            name='av',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Zoo.aviary'),
        ),
        migrations.AddField(
            model_name='kind_of_animal',
            name='countries',
            field=models.ManyToManyField(null=True, to='Zoo.country_of_residence'),
        ),
        migrations.AddField(
            model_name='kind_of_animal',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Zoo.feed'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Zoo.job_title'),
        ),
    ]
