# Generated by Django 5.0.6 on 2024-06-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0010_kind_of_animal_staffs_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ward_animals',
        ),
        migrations.AddField(
            model_name='user',
            name='ward_animals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Zoo.kind_of_animal'),
        ),
    ]
