# Generated by Django 5.0.6 on 2024-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0011_remove_user_ward_animals_user_ward_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kind_of_animal',
            name='staffs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ward_animals',
        ),
        migrations.AddField(
            model_name='user',
            name='ward_animals',
            field=models.ManyToManyField(to='Zoo.kind_of_animal'),
        ),
    ]
