# Generated by Django 5.0.6 on 2024-06-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0014_ticket_useddiscounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Zoo.job_title'),
        ),
    ]
