# Generated by Django 5.0.6 on 2024-06-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0015_alter_user_job_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(),
        ),
    ]
