# Generated by Django 5.0.6 on 2024-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0019_ticket_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_of_visit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
