# Generated by Django 5.0.6 on 2024-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0020_alter_ticket_date_of_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('website', models.URLField()),
            ],
        ),
    ]
