# Generated by Django 5.0.6 on 2024-10-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0022_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
