# Generated by Django 5.0.6 on 2024-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0006_aviary_country_of_residence_feed_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind_of_animal',
            name='countries',
            field=models.ManyToManyField(to='Zoo.country_of_residence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ward_animals',
            field=models.ManyToManyField(to='Zoo.kind_of_animal'),
        ),
    ]
