# Generated by Django 5.0.6 on 2024-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0018_alter_promocode_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
